name: 'r2py'
description: 'Convert R code to python with rpy2'
inputs:
  name:
    description: 'GitHub username or organization name'
    required: true
  repo:
    description: 'Name of repo to convert'
    required: true
  email:
    description: 'GitHub email'
    required: true
  pat:
    description: 'GitHub personal access token'
    required: true
  org:
    description: 'Provide a truthy value indicate organization, falsy value to indicate personal account'
    required: false
    default: '1'
  py_repo:
    description: 'Name of repo to push python package to'
    required: false
    default: '?'
runs:
  using: 'node12'
  main: 'dist/index.js'